apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | b64enc | quote }}
